all:
	python translate.py algtop.mookdown algtop.html
	python translate.py geo.mookdown geo.html
	python translate.py genfunc.mookdown genfunc.html
	python translate.py quant.mookdown quant.html
	python translate.py rep.mookdown rep.html
	python translate.py modules.mookdown modules.html
	python translate.py manifold.mookdown manifold.html
	python translate.py quantcomp.mookdown quantcomp.html
	python translate.py rando.mookdown rando.html

