all:
	python3 translate.py algtop
	python3 translate.py boundary
	python3 translate.py diffgeo 
	python3 translate.py difftop 
	python3 translate.py geo
	python3 translate.py genfunc
	python3 translate.py infoflow 
	python3 translate.py pbj 
	python3 translate.py quant
	python3 translate.py rep
	python3 translate.py language
	python3 translate.py ml 
	python3 translate.py modules
	python3 translate.py quantcomp
	python3 translate.py rando
	python3 translate.py _routine

routine:
	python3 translate.py _routine

lang:
	python3 translate.py language
