rocks:
	python3 translate.py rocks

all:
	python3 translate.py constitution
	python3 translate.py manifold
	python3 translate.py rocks
	python3 translate.py statmech
	python3 translate.py turing
	python3 translate.py probly
	python3 translate.py smalin

lang:
	python3 translate.py language
