var music = [
["Bach"         , "English Suite 2 --- Prelude"     , "Gould"       ,   4.5, 0  , 0  , 0  , 0  , ""],
["Bach"         , "Keyboard Partita 1"              , "Tureck"      ,   5.5, 0  , 0  , 0  , 0  , ""],
["Bach"         , "Keyboard Partita 4"              , "Tureck"      ,   6.5, 0  , 0  , 0  , 0  , ""],
["Bach"         , "Violin Concerto 2 ('E Major')"   , ""            ,   7.5, 0  , 0  , 0  , 0  , ""],
["Bach"         , "Partita 2 for Unaccomp. Violin"  , "Milstein"    ,   8.5, 0  , 0  , 0  , 0  , ""],
["Bach"         , "Trio Sonata 1"                   , ""            ,   9.5, 0  , 0  , 0  , 0  , ""],
["Bach"         , "English Suite 2 --- Prelude"     , "Gould"       ,  10.5, 0  , 0  , 0  , 0  , ""],
["Bach"         , "English Suite 4 --- Prelude"     , "Gould"       , 100.0, 0  , 0  , 0  , 0  , ""],
["Bach"         , "English Suite 4 --- Gigue"       , "Gould"       ,   2.3, 0  , 0  , 0  , 0  , ""],
["Bach"         , "English Suite 5 --- Prelude"     , "Gould"       ,   4.7, 0  , 0  , 0  , 0  , ""],
["Bach"         , "English Suite 6 --- Gavottes"    , "Gould"       , 100.5, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 1 --- Allemande"    , "Gould"       ,   2.5, 0  , 1  , 0  , 0  , ""],
["Bach"         , "French Suite 1 --- Menuetts"     , "Gould"       , 100.0, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 1 --- Gigue"        , "Gould"       , 100.0, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 3 --- Allemande"    , "Gould"       , 100.0, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 3 --- Gigue"        , "Gould"       ,   1.6, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 4 --- Allemande"    , "Gould"       ,   1.1, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 4 --- Gigue"        , "Gould"       ,   1.9, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 5 --- Allemande"    , "Gould"       ,   1.8, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 5 --- Gavotte"      , "Gould"       ,   0.7, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 5 --- Loure"        , "Gould"       ,   1.1, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 5 --- Gigue"        , "Gould"       ,   2.4, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Suite 6 --- Gigue"        , "Gould"       ,   2.1, 0  , 1  , 1  , 2  , ""],
["Bach"         , "French Overture --- Bourees"     , "Gould"       , 100.0, 0  , 0  , 0  , 0  , ""],
["Bach"         , "French Overture --- Echo"        , "Gould"       , 100.0, 0  , 0  , 0  , 0  , ""],
["Beethoven"    , "Piano Concerto 5 ('Emperor')"    , "Gould"       ,  36.0, 0  , 1  , 0  , 1  , ""],
["Mahler"       , "Symphony 3 --- Finale"           , ""            ,   7.3, 0  , 1  , 0  , 0  , ""],
["Mahler"       , "Symphony 5 --- Adagietto"        , "Bernstein"   ,  12.1, 0  , 2  , 1  , 0  , ""],
];
